name: elpcd_dart
description: 'Ferramenta para criação de PCDs e TTDs'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  csv: ^5.0.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.0
  file_saver: ^0.0.6
  flutter_bloc: ^7.0.0
  flutter_simple_treeview: ^3.0.0-nullsafety.1
  hive: ^2.0.3
  hive_flutter: ^1.0.0
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.12.2
  hive_generator: ^1.0.1
  pedantic: ^1.11.0

flutter:
  uses-material-design: true
  assets:
    - assets/gedalogo_270x270.png
